image: ubuntu:latest

before_script:
  - apt-get update
  - apt-get install -y wget git build-essential

stages:
  - build
  - build_release

build:
  stage: build
  script:
    - ./build.sh
  artifacts:
    paths:
      - output_dir/*
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_TAG == null'

build_release:
  stage: build_release
  script:
    - ./build.sh
  artifacts:
    paths:
      - output_dir/*
    expire_in: 100 yrs
  rules:
    - if: '$CI_COMMIT_TAG != null'
