language: generic

script:
- bash build.sh

os: linux
dist: bionic
# nothing, just to trigger a new github actions build

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: output_dir/*
  overwrite: true
  draft: false
